# Generated by Django 5.0.2 on 2024-02-08 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEvenements', '0002_alter_evenement_proprietaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('physique', 'Physique'), ('morale', 'Morale')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='evenement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionEvenements.organisateur'),
        ),
    ]
